services:
  frontend:
    build:
      context: frontend
    container_name: "daily_review"
    image: dailyreview/frontend
    expose:
      - "80"
    ports:
      - "80:80"
    networks:
      - inside

  backend:
    build:
      context: backend
    container_name: "backend"
    image: dailyreview/backend
    expose:
      - "9000"
    networks:
      - inside
      - outside

networks:
  outside:
    driver: bridge
  inside:
    name: "daily_review"




