from questions_config import EXERCISE_QUESTIONS, LECTURE_QUESTIONS, PERSONAL_LEARN_QUESTIONS, \
    PHYSICAL_TRAINING_QUESTIONS

REVIEW_TYPE_TO_QUESTIONS = {
    'ע"ע': EXERCISE_QUESTIONS,
    'הרצאה': LECTURE_QUESTIONS,
    'ל"ע': PERSONAL_LEARN_QUESTIONS,
    'א"ג': PHYSICAL_TRAINING_QUESTIONS,
}

HIVE_USERNAME = "admin"
HIVE_PASSWORD = "AdMataiHabra"
HIVE_URL = "https://10.0.10.23"
MISUV_SUBJECT_SYMBOL = "M3"
MISUV_SUBJECT_NAME = "מישוב3"
MISUV_MODULE_NAME = "מישוב יומי"
